require 'bundler/setup'
Bundler.require
require_all 'app'
require 'pry'
require_relative '../app/models/guest.rb'
require_relative '../app/models/listing.rb'
require_relative '../app/models/trip.rb'
require_relative '../app/models/bakery.rb'
require_relative '../app/models/dessert.rb'
require_relative '../app/models/ingredient.rb'
